const { Resend } = require("resend");

const resend = new Resend(process.env.RESEND_API_KEY);

async function sendEmail(recipient, summary, fileName) {
  const subjectLine = fileName
    ? `Your Analysis Report — ${fileName}`
    : "Your Dataset Analysis Report";

  const htmlBody = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 680px; margin: 0 auto; padding: 32px; background-color: #0a0a0b; color: #e4e4e7;">
      <div style="border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 24px; margin-bottom: 24px;">
        <h1 style="font-size: 20px; font-weight: 600; color: #ffffff; margin: 0 0 4px 0;">InsightFlow</h1>
        <p style="font-size: 13px; color: #a1a1aa; margin: 0;">AI-Powered Dataset Analysis</p>
      </div>
      ${fileName ? `<p style="font-size: 13px; color: #a1a1aa; margin-bottom: 16px;">Report for: <strong style="color: #e4e4e7;">${fileName}</strong></p>` : ""}
      <div style="background-color: #141416; border: 1px solid rgba(255,255,255,0.08); border-radius: 8px; padding: 24px; white-space: pre-wrap; line-height: 1.7; font-size: 14px; color: #d4d4d8;">
${summary}
      </div>
      <p style="font-size: 12px; color: #71717a; margin-top: 24px; text-align: center;">Generated by InsightFlow &bull; AI-powered dataset summarization</p>
    </div>
  `;

  const { data, error } = await resend.emails.send({
    from: "InsightFlow <onboarding@resend.dev>", // use your verified domain once set up
    to: recipient,
    subject: subjectLine,
    html: htmlBody,
    text: summary,
  });

  if (error) {
    throw new Error(`Resend error: ${error.message}`);
  }

  console.log("📧 Email sent:", data.id, "to:", recipient);
}

module.exports = sendEmail;