const https = require("https");
const { marked } = require("marked");

// Convert markdown to plain semantic HTML first (no custom renderer —
// avoids breaking across marked's differing Renderer API versions),
// then inject inline styles by replacing opening tags directly.
// Inline styles are required because most email clients strip <style>
// blocks and ignore CSS classes.
function markdownToEmailHtml(markdownText) {
  const rawHtml = marked.parse(markdownText || "");

  return rawHtml
    .replace(/<h[1-3]>/g, '<h3 style="font-size: 15px; font-weight: 700; letter-spacing: 0.5px; text-transform: uppercase; color: #ff6600; margin: 28px 0 12px 0; padding-bottom: 8px; border-bottom: 1px solid rgba(255,255,255,0.08);">')
    .replace(/<\/h[1-3]>/g, "</h3>")
    .replace(/<p>/g, '<p style="font-size: 14px; line-height: 1.7; color: #d4d4d8; margin: 0 0 12px 0;">')
    .replace(/<strong>/g, '<strong style="color: #ffffff; font-weight: 600;">')
    .replace(/<ul>/g, '<ul style="margin: 0 0 16px 0; padding-left: 20px;">')
    .replace(/<ol>/g, '<ol style="margin: 0 0 16px 0; padding-left: 20px;">')
    .replace(/<li>/g, '<li style="font-size: 14px; line-height: 1.7; color: #d4d4d8; margin-bottom: 8px;">')
    .replace(/<hr>/g, '<hr style="border: none; border-top: 1px solid rgba(255,255,255,0.08); margin: 24px 0;" />')
    .replace(/<table>/g, '<table style="width: 100%; border-collapse: collapse; margin: 0 0 16px 0;">')
    .replace(/<th>/g, '<th style="text-align: left; padding: 8px; font-size: 13px; color: #ff6600; border-bottom: 1px solid rgba(255,255,255,0.08);">')
    .replace(/<td>/g, '<td style="padding: 8px; font-size: 14px; color: #d4d4d8; border-bottom: 1px solid rgba(255,255,255,0.05);">');
}

async function sendEmail(recipient, summary, fileName) {
  const subjectLine = fileName
    ? `Your Analysis Report — ${fileName}`
    : "Your Dataset Analysis Report";

  const summaryHtml = markdownToEmailHtml(summary);

  const htmlBody = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 680px; margin: 0 auto; padding: 32px; background-color: #0a0a0b; color: #e4e4e7;">
      <div style="border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 24px; margin-bottom: 24px;">
        <h1 style="font-size: 20px; font-weight: 600; color: #ffffff; margin: 0 0 4px 0;">InsightFlow</h1>
        <p style="font-size: 13px; color: #a1a1aa; margin: 0;">AI-Powered Dataset Analysis</p>
      </div>
      ${fileName ? `<p style="font-size: 13px; color: #a1a1aa; margin-bottom: 16px;">Report for: <strong style="color: #e4e4e7;">${fileName}</strong></p>` : ""}
      <div style="background-color: #141416; border: 1px solid rgba(255,255,255,0.08); border-radius: 8px; padding: 24px;">
${summaryHtml}
      </div>
      <p style="font-size: 12px; color: #71717a; margin-top: 24px; text-align: center;">Generated by InsightFlow &bull; AI-powered dataset summarization</p>
    </div>
  `;

  // Brevo's transactional email API expects sender as an object, and
  // recipients as an array of { email } objects — not a flat "from"/"to" string.
  const payload = JSON.stringify({
    sender: {
      name: process.env.BREVO_SENDER_NAME || "InsightFlow",
      email: process.env.BREVO_SENDER_EMAIL, // e.g. "sulabhsaluja111@gmail.com"
    },
    to: [{ email: recipient }],
    subject: subjectLine,
    htmlContent: htmlBody,
    textContent: summary, // plain-text fallback stays as raw markdown-ish text — fine for the fallback view
  });

  return new Promise((resolve, reject) => {
    const req = https.request(
      {
        hostname: "api.brevo.com",
        path: "/v3/smtp/email",
        method: "POST",
        headers: {
          "api-key": process.env.BREVO_API_KEY,
          Accept: "application/json",
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(payload),
        },
      },
      (res) => {
        let body = "";
        res.on("data", (chunk) => (body += chunk));
        res.on("end", () => {
          if (res.statusCode >= 200 && res.statusCode < 300) {
            console.log("📧 Email sent via Brevo to:", recipient);
            resolve();
          } else {
            reject(new Error(`Brevo API error ${res.statusCode}: ${body}`));
          }
        });
      }
    );

    req.on("error", reject);
    req.write(payload);
    req.end();
  });
}

module.exports = sendEmail;